{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: "{{ .Values.postgres.image }}"
          ports:
            - containerPort: {{ .Values.postgres.service.port }}
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.db.name }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.db.user }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.db.password }}"
{{- end }}
